name: We Build SG LIVE
description: We Build SG LIVE - A live conversation with geeks in town on building, learning and sharing!
author: Chinmay and Sayanee
email: sayanee@gmail.com
tags: live, show, audio, podcast, developers, makers, designers, software, hardware
feed: http://feeds.feedburner.com/WeBuildLive
destination: ./_publish
permalink: /:title
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'readme.md', 'js', 'scripts']
markdown: kramdown
url: //live.webuild.sg
timezone:    Asia/Singapore
encoding:    UTF-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

default_logo : https://assets.webuild.sg/logo-200.jpg
default_day : Sat
default_time : 11am

next_guest: "U-Zyn Chua"
next_episode: "050"
next_podcast_start_time: 2017-09-02 11:00 +0800
next_podcast_end_time: 2017-09-02 12:00 +0800
next_profile: /img/050-uzyn-chua-profile.jpg
next_topic: Bitcoin, Ethereum, blockchain and decentralization.
next_connect: 'Connect with U-Zyn on <a href="https://twitter.com/uzyn">Twitter</a>, <a href="https://github.com/uzyn">GitHub</a> and <a href="http://uzyn.com/">website</a>!'
